### ISSUE TITLE
Use proper KDoc syntax

### ISSUE THREAD

**Issue by SPC-code** [ZhigalskiiIvan/ServerRequest#1]
https://github.com/ZhigalskiiIvan/ServerRequest/blob/f1bf2ae4f428add08ac2cfaeeb1b8a39c6da860e/src/main/kotlin/Main.kt#L8

KDoc reference is here: https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax

**Comment by ZhigalskiiIvan** [comment]
flashback from python

**Comment by ZhigalskiiIvan** [comment]
Еще есть проблема, что программа не получает ответа с сервера после отправки суммы, но не понимаю, в чем дело
